language: node_js
node_js:
- 14
deploy:
  provider: npm
  email: anton@mokr.org
  api_key:
    secure: GyYyCIBEY2nFcQJjErcmkiSh1H+9+3ufOJM5O8qTKM36K1r+qmT7qyIOaLWvsIUwva58gsP9KUl2Rmazy8zPOC7HASo91yWtFfiIrkPrpHCxx/y1SMjBKXmdMxF/OuvJs0SylM3a+Bmvk5Z8ndXR/08c3BvUayF2Wyv4oYUndqDL3nJGHsRVpCEaeF2Yo0rSiij2gzGYdq9iijdgMmSNNW8PufzZVH6AnzHXRvW0eKo1HAqKZE1QqP4u/VBVvgr9lUrYEgcrExAAZ+rxp+7F50mTX1ow+GyzgSiN2L6SYeC3KQhnMV1fyImu2huTLSmda0uG71cd+jqYSACfsIQ8d980fVkBTh5YYRv97Qe7md3SDiNPQIxluOrwLcDKjlujxs9r/sYa0/kAgwj/utYDZuR+7mIHMFcTgBB3IifOcnm0tzYhjKah364a0G5f5f2qveejIK5d6gi+1k3MSb3LqYEbvInVWjR83eFKLHrWRfnGtI/9Pa/HN4j5lhwi/PLDSSTW6qDXJHoG1Y+8ZrIrVXFZ3XWkozac8qQ+fu/3aEXxhjpS3dFtYheRpIP6w597VmAyGfPFArmeZv8qlc/JsOkvWUMAehjJKO9d6O0A9orCd3sta1z2Yp4DmRuDd3alpe9qfjafqEP4TUvirnnQBjID/TKdOzaDyMJ+Sy5tQUE=
  on:
    tags: true
    repo: amokrushin/gitlab-ci-lint-es
  skip_cleanup: 'true'
